# Let's Encrypt SSL 인증서 자동 설정을 위한 Docker Compose 설정
# 프로덕션 환경에서 사용

version: '3.8'

services:
  # Certbot for Let's Encrypt SSL certificates
  certbot:
    image: certbot/certbot:latest
    container_name: vibemusic-certbot
    volumes:
      - ./ssl:/etc/letsencrypt
      - ./certbot-webroot:/var/www/certbot
    command: >
      certonly --webroot
      --webroot-path=/var/www/certbot
      --email your-email@example.com
      --agree-tos
      --no-eff-email
      --force-renewal
      -d your-domain.com
      -d www.your-domain.com
    depends_on:
      - nginx
    networks:
      - vibemusic-network

  # SSL 인증서 자동 갱신을 위한 cron 컨테이너
  certbot-renew:
    image: certbot/certbot:latest
    container_name: vibemusic-certbot-renew
    volumes:
      - ./ssl:/etc/letsencrypt
      - ./certbot-webroot:/var/www/certbot
    command: >
      sh -c "
        while :; do
          certbot renew --webroot --webroot-path=/var/www/certbot --quiet
          sleep 12h
        done
      "
    depends_on:
      - certbot
    restart: unless-stopped
    networks:
      - vibemusic-network

volumes:
  certbot-webroot:
    driver: local

networks:
  vibemusic-network:
    external: true
    name: vibemusic-network